# Generated by Django 6.0.2 on 2026-03-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('ultima_alteracao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela Salarial',
                'verbose_name_plural': 'Tabelas Salariais',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='simreajuste.tabelasalarial')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['tabela', 'numero'],
                'unique_together': {('tabela', 'numero')},
            },
        ),
    ]
